config/routes.rb
Sos::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  # Strona startowa
  devise_scope :user do
    authenticated :user do # jeśli zalogowany
     root :to => 'tasks#index', as: :authenticated_root
   end
   unauthenticated :user do #jeśli nie zalogowany
     root :to => 'devise/sessions#new', as: :unauthenticated_root
   end
  end

  # Linki do panelu administracyjnego
  namespace :admin do
    # get "home/index" # Strona główna panelu adminisracyjnego
    get "dashboard" => 'home#index', as: :dashboard # Strona główna panelu adminisracyjnego
    resources :users
    get 'users/:id/gen_password' => 'users#gen_new_pass', as: :new_password_gen
    resources :roles, only: [:index, :edit, :update]
    get "logs" => 'logs#list', as: :logs #Logi
  end

  resources :tasks do
   resources :items

   # Odepnij sprzęt od zlecenia
   get 'items/:id/remove_from_task' => 'items#remove_from_task', as: :remove_item

   # Przypnij sprzęt do zlecenia
   get 'items/:id/add_to_task' => 'items#add_to_task', as: :add_item

   # Lista klientów do możliwych do dodania do zgłoszenia
   get '/:id/clients' => 'users#clients_list_to_task', as: :clients, on: :collection
   get '/:task_id/client/new' => 'users#new_client_to_task', as: :new_client, on: :collection
   get '/:task_id/clients/:id/add_to_task' => 'users#add_to_task', as: :add_client, on: :collection
   get '/:task_id/clients/:id/remove_from_task' => 'users#remove_from_task', as: :remove_client, on: :collection
   post '/clients' => 'users#create_task_client'
  end

  get 'archive' => 'tasks#archive', as: :archive

  resources :users

  # linki do klientów, zwenętrznej
  get 'clients' => 'users#clients', as: :clients_list
  get 'client/new' => 'users#new_client', as: :client_new
  post 'users/create_client'
  get 'client/:id' => 'users#show_client', as: :show_client
  get 'client/:id/edit' => 'users#edit', as: :edit_client
  delete 'client/:id' => 'users#destroy', as: :del_client
  put 'client/:id' => 'users#update'
  patch 'client/:id' => 'users#update' 
  get 'clients/:id/new/password' => 'users#pass_restart', as: :password_gen

  # linki do sprzętów, zwenętrznej
  get 'items' => 'items#items_list', as: :items_list
  get 'item/new' => 'items#item_new', as: :item_new
  post 'items/item_create'
  get 'item/:id' => 'items#item_show', as: :show_item
  get 'item/:id/edit' => 'items#item_edit', as: :edit_item
  delete 'item/delete/:id' => 'items#item_destroy', as: :del_item
  put 'item/:id/update' => 'items#item_update'
  patch 'item/:id/update' => 'items#item_update' 

  # Linki zarządzające profilem użytkownika
  get 'profile/:id' => 'users#profile', as: :profile
  get 'profile/:id/edit' => 'users#edit_profile', as: :profile_edit
  get 'profile/:id/password' => 'users#change_password', as: :profile_password
  put 'profile/:id' => 'users#profile_update'  # update profilu
  patch 'profile/:id' => 'users#profile_update' # update profilu
  put 'profile/:id/password' => 'users#password_update' # zmiana hasła
  patch 'profile/:id/password' => 'users#password_update' # zmiana hasła

end

app/models/task.rb
class Task < ActiveRecord::Base
  # asocjacje
  has_many :cards
  has_many :items, :through => :cards

  belongs_to :status
  belongs_to :type

  belongs_to :user
  # walidacje pól
  validates  :description, presence: true
  validates  :description, length: { minimum: 3, too_short: "Minimalna ilość znaków: %{count}.", maksimum: 300, too_long: "Maksymalna ilość znaków: %{count}."}
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!
  before_action :find_task, only: [:show, :edit, :destroy, :update]
  authorize_resource  :except => :archive

  def index
    if current_user.role.name == 'client'
      @tasks = Task.paginate(:page => params[:page], :per_page => 10).order(created_at: :desc).where('archive = ?', false).where('user_id = ?', current_user.id)
    elsif current_user.role.name ==  'employe'
      @tasks = Task.paginate(:page => params[:page], :per_page => 10).order(created_at: :desc).where('archive = ?', false).where('responsible = ?', current_user.full_name)
    else
	     @tasks = Task.paginate(:page => params[:page], :per_page => 10).order(created_at: :desc).where('archive = ?', false)
    end
  end

  def archive
    if current_user.role.name == 'client'
      @tasks = Task.paginate(:page => params[:page], :per_page => 10).where('user_id = ?', current_user.id ).where('archive = ?', true)
    else
      @tasks = Task.paginate(:page => params[:page], :per_page => 10).where('archive = ?', true)
    end
      authorize! :read, :task
  end

  def show

  end

  def edit
  end

  def new
	 @task = Task.new
  end

  def create
      if current_user.role.name == 'menager'
        @task = Task.new(params_for_menager)
      elsif current_user.role.name == 'admin'
        @task = Task.new(params_for_menager)
      else
        @task = Task.new(task_params_for_employee)
      end
	 # @task = Task.new(task_params)
   @task.author = current_user.full_name # imie i nazwisko osoby tworzącej zlecenie
   @task.archive = false
    respond_to do |format|
      if @task.save
        format.html { redirect_to clients_tasks_path(@task), notice: 'Gratulacje! Zgłoszenie serwisowe zostało poprawnie utworzone.' }
        format.json { render action: 'index', status: :created, location: @task }
        new_log("Utworzono nowe zgłoszenie serwisowe o id: #{@task.id}", "Zgłoszenie")
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @task.lock != true
      if current_user.role.name == 'menager'
        @task.update(params_for_menager)
      elsif current_user.role.name == 'admin'
        @task.update(params_for_menager)
      else
  	    @task.update(task_params_for_employee)
      end

      if @task.status_id == 7
         @task.archive = true
         @task.lock = true
         new_log("Zgłoszenie o id: #{@task.id}, zostało zakończone i przeniesione do archiwum.", "Zgłoszenie")
         TaskMailer.closed(@task.user, @task).deliver
        elsif @task.status_id  == 6
          @task.archive = true
          new_log("Zgłoszenie o id: #{@task.id}, zostało anulowane i przeniesione do archiwum.", "Zgłoszenie")
        else
          @task.archive = false
          @task.lock = false
      end

      respond_to do |format|
        if @task.save

          new_log("Zaktualizowano zgłoszenie serwisowe o id: #{@task.id}", "Zgłoszenie")
          format.html { redirect_to tasks_path, notice: 'Zgłoszenie serwisowe zostało poprawnie zaktualizowane.' }
          format.json { render action: 'index', status: :created, location: @task }
        else
          format.html { render action: 'show' }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
     else
        redirect_to @task, alert: "Mnie można edytować zakończonego zgłoszenia serwisowego!"
     end
  end

  def destroy
  new_log("Usunięto zgłoszenie serwisowe o id: #{@task.id}", "Zgłoszenie")
   @task.destroy
    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Zlecenie zostało usunięte.' }
        format.json { render action: 'index', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end



private
# Dopisać parametry do zapisów
  def task_params
	 params.require(:task).permit(:description, :type_id, :status_id, :end_task, :note, :author_id, :archive, :lock)
  end

  def task_params_for_employee
   params.require(:task).permit(:description, :type_id, :status_id, :end_task, :note, :author_id, :archive, :lock)
  end

  def params_for_menager
   params.require(:task).permit(:description, :type_id, :status_id, :end_task, :note, :author_id, :archive, :lock, :responsible)
  end

# Znajdź zgłoszenia po id
  def find_task
	 @task = Task.find(params[:id])
  end
end

app/helpers/task_helper.rb
module TaskHelper

# helper kolorujący wiersz w tabeli w zależności od terminu zgłoszenia
	def timesup_class(end_date)
		if end_date <= 1.day.from_now
			return ("class = \"danger text-danger\"").html_safe
		elsif end_date <= 7.day.from_now
			return ("class = \"warning text-warning\"").html_safe
		end

	end

# helper dodający label przy terminie końca zlecenia
	def timesup_label(end_date)
		if end_date <= 1.days.from_now
			return ("<span class=\"label label-danger\">Opóźnienie !</span>").html_safe
		elsif end_date <= 7.days.from_now
			return ("<span class=\"label label-warning\">Termin !</span>").html_safe
		end
	end

# heler do wyświetlania alertów wyświetlanych w widoku szczegółów zgłoszenia
	def timesup_showpage(end_date)
		if end_date <= 1.day.from_now
			return ("<div class=\"alert alert-danger\" role=\"alert\"><strong>UWAGA!</strong> Zgłoszenie jest już opóźnione! Proszę o natychmiastową reakcję!</div>").html_safe
		elsif end_date <= 7.day.from_now
			return ("<div class=\"alert alert-warning\" role=\"alert\"><strong>UWAGA!</strong> Zbliża się termin końcowy zgłoszenia!</div>").html_safe
		end
	end

# wyświetl alert przypominający o terminach i opóźnieniach
	def timesup_alert_danger
		if @tasks.where( 'end_task <= ?', 1.days.from_now).count == 1
			return ("<div class=\"alert alert-danger\" role=\"alert\"><strong>UWAGA!</strong> Masz <strong>#{@tasks.where( 'end_task <= ?', 1.days.from_now).count}</strong>-no zgłoszenie które jest już opóźnione!</div>").html_safe
		elsif @tasks.where( 'end_task <= ?', 1.days.from_now).count > 1
			return ("<div class=\"alert alert-danger\" role=\"alert\"><strong>UWAGA!</strong> Masz <strong>#{@tasks.where( 'end_task <= ?', 1.days.from_now).count}</strong> zgłoszenia które są już opóźnione!</div>").html_safe
		end
	end

 # Zmienić nazwe helpera, podaje liczbę zgłodzeń z terminem oraz opóźnieniem (Należy odjąć liczbę opóźnionych !)
	def timesup_alert_warning
		if (@tasks.where( 'end_task <= ?', 7.days.from_now).count)-(@tasks.where( 'end_task <= ?', 1.days.from_now).count) != 0
			# Jeśli jest tylko jedno takie zlecenie
			if (@tasks.where( 'end_task <= ?', 7.days.from_now).count)-(@tasks.where( 'end_task <= ?', 1.days.from_now).count) == 1 
				return ("<div class=\"alert alert-warning\" role=\"alert\"><strong>UWAGA!</strong> Masz <strong>#{(@tasks.where( 'end_task <= ?', 7.days.from_now).count)-(@tasks.where( 'end_task <= ?', 1.days.from_now).count)}</strong>-no zgłoszenie któremu wkrótce skończy się termin realizacji!</div>").html_safe
			# Jeśli do końca zgłoszenia pozostał tydzień
			elsif (@tasks.where( 'end_task <= ?', 7.days.from_now).count)-(@tasks.where( 'end_task <= ?', 1.days.from_now).count) > 0 
				return ("<div class=\"alert alert-warning\" role=\"alert\"><strong>UWAGA!</strong> Masz <strong>#{(@tasks.where( 'end_task <= ?', 7.days.from_now).count)-(@tasks.where( 'end_task <= ?', 1.days.from_now).count)}</strong> zgłoszenia którym wkrótce skończy się termin realizacji!</div>").html_safe
			end
		end 
	end

	def did_client_fly_with_us(fly)
		if fly == nil
			return ("<div class=\"alert alert-danger\" role=\"alert\"><strong>UWAGA!</strong> Do zgłoszenia nie masz dodane aktualnie żadnego klienta! Dodaj go czym prędzej !</div>").html_safe
		end
	end

	def you_have_my_sword(sword)
		if sword.empty?
			return ("<div class=\"alert alert-warning\" role=\"alert\"><strong>UWAGA!</strong> Do zgłoszenia nie masz przypisane aktualnie żadnego sprzętu! Proszę dodaj sprzęt do serwisowania czym prędzej!</div>").html_safe
		end
	end
end

app/views/tasks/_table_tasks.html.erb
					<div class="table-responsive">
						<table class="table table-bordered text-center">
							<tr>
								<th>#</th>
								<th>Status</th>
								<th>Typ</th>
								<th>Utworzono</th>
								<th>Termin</th>
								<% if can? :update, Task %><th>Zmodyfikowano</th><% end %>
								<th>Akcje</th>
							</tr>
							<% @tasks.each do |task| %>
							<tr>
								<td><%= link_to task.id, task %></td>
								<td><%= task.status.name %></td>
								<td><%= task.type.name %></td>
								<td><%= l task.created_at, format: :long %></td>
								<td><%= l task.end_task, format: :long %></td>
								<% if can? :update, Task %>
									<td><%= l task.updated_at, format: :long %></td>
								<% end %>
								<td>
									<%= link_to [task, @item], class: "btn btn-primary btn-sm" do %>
										<span class="glyphicon glyphicon-folder-open"></span>
									<% end %>
									
									<% if task.lock != true %>
										<% if can? :update, Task %>
											 <%= link_to edit_task_path(task), class: "btn btn-warning btn-sm" do %>
													<span class="glyphicon glyphicon-pencil"></span>
											 <% end %>
										<% end %>
									<% end %>

									<% if can? :destroy, Task %>
										<%= link_to task_path(task), method: :delete, data: { confirm: "Czy na pewno chcesz usunąć to zlecenie?"}, class: "btn btn-danger btn-sm" do %>
											<span class="glyphicon glyphicon-trash"></span>
										<% end %>
									<% end %>
								</td>
							</tr>
							<% end # koniec bloku%>
						</table>
					</div> <!-- end table-responsive -->

app/views/tasks/_task_left_nav.html.erb
			<div class="col-md-2">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title text-center">Menu</h3>
					</div>
					<div class="panel-body">
							<%= link_to authenticated_root_path, class: "btn btn-primary btn-block" do %>
								<span class="glyphicon glyphicon-home"></span> Strona Główna
							<% end %>
						<% if can? :create, Task %>
							<%= link_to new_task_path, class: "btn btn-primary btn-block" do %>
								<span class="glyphicon glyphicon-plus"></span> Utwórz nowe zgłoszenie
							<% end %>
						<% end %>
							<%= link_to archive_path, class: "btn btn-primary btn-block" do %>
								<i class="fa fa-archive"></i> Archiwum zgłoszeń
							<% end %>												
					</div>
				</div>
			</div>

app/views/tasks/archive.html.erb
<% provide(:title, 'Archiwum zgłoszeń serwisowych') %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-md-2">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title text-center">Menu</h3>
				</div>
				<div class="panel-body">
						<%= link_to authenticated_root_path, class: "btn btn-primary btn-block" do %>
							<span class="glyphicon glyphicon-home"></span> Strona Główna
						<% end %>
					<% if can? :create, Task %>
						<%= link_to new_task_path, class: "btn btn-primary btn-block" do %>
							<span class="glyphicon glyphicon-plus"></span> Utwórz nowe zgłoszenie
						<% end %>
					<% end %>
						<%= link_to archive_path, class: "btn btn-primary btn-block" do %>
							<i class="fa fa-archive"></i> Archiwum zgłoszeń
						<% end %>												
				</div>
			</div>
		</div>
		<div class="col-md-10">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title text-center">Lista zakończonych zgłoszeń serwisowych:</h3>
				</div>
				<div class="panel-body">
					<p class="text-center">
				<div class="well well-lg text-center">
						<% if current_user.role.name == "client" %>
							Poniżej znajduje się lista wszystkich twoich anulowanych oraz zakończonych zgłoszeń serwisowych.
						<% else %>
							Poniżej znajduje się lista wszystkich anulowanych oraz zakończonych zgłoszeń serwisowych.
						<% end %>
				</div>
					</p>		

				<!-- Tabela z listą zgłoszeń -->
			
				<% if current_user.role == 'client' %>
					<% if Task.where('archive = ?', true).where('user_id = ?', current_user.id).count > 0 # Jeślli liczba zleceń jest inna niż 0 %>
						<%= render 'table_tasks' %>
					<% else %>	
						<div class="well well-lg text-center">Aktualnie nie ma żadnych zgłoszeń zarchiwizowanych.</div>
					<% end # koniec if %>
				<% else %>
					<% if Task.where('archive = ?', true).count > 0 # Jeślli liczba zleceń jest inna niż 0 %>
						<%= render 'table_tasks' %>
					<% else %>	
						<div class="well well-lg text-center">Aktualnie nie ma żadnych zgłoszeń zarchiwizowanych.</div>
					<% end # koniec if %>

				<% end %>
				</div> <!-- end panel-body -->
				<div class="panel-footer">
					<span class="text-center">
						<%= will_paginate @tasks %>
					</span>
				</div>
			</div><!-- end panel -->
		</div><!-- end col-md-9 -->
	</div> <!-- row-fluid -->
</div> <!-- /container -->

app/views/tasks/edit.html.erb
<% provide(:title, "Edycja zlecenia nr: #{@task.id}") %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-md-12">

			<ol class="breadcrumb">
			 	<li><%= link_to "Lista zleceń", tasks_path %></li>
			 	<li class="active">Edycja zlecenia</li>
			</ol>
		</div>
	</div>
	<div class="row-fluid">
					<div class="col-md-2">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title text-center">Menu</h3>
					</div>
					<div class="panel-body">
							<%= link_to authenticated_root_path, class: "btn btn-primary btn-block" do %>
								<span class="glyphicon glyphicon-home"></span> Strona Główna
							<% end %>
						<% if can? :create, Task %>
							<%= link_to new_task_path, class: "btn btn-primary btn-block" do %>
								<span class="glyphicon glyphicon-plus"></span> Stwórz nowe zgłoszenie
							<% end %>
						<% end %>
							<%= link_to archive_path, class: "btn btn-primary btn-block" do %>
								<i class="fa fa-archive"></i> Archiwum zgłoszeń
							<% end %>	
							<%= link_to tasks_path, class: "btn btn-primary btn-md btn-block"  do %>
								<span class="glyphicon glyphicon-arrow-left"></span> Wróć do listy zgłoszeń
							<% end %>											
					</div>
				</div>
			</div>
			<div class="col-md-10" >
			<div class="panel panel-default">
				<div class="panel-heading">
		    		<h3 class="panel-title text-center">Edycja zgłoszenia serwisowego:</h3>
		  		</div>
			  <div class="panel-body">
				<div class="well well-lg text-center">
					Poniżej znajduje się formularz edycji zgłoszenia serwisowego. W tym miejscu dokonujemy zmiany <strong>statusu</strong> zgłoszenia oraz jego terminu realizacji.
				</div>

				<%= render 'task_form' %>

			  </div>
			</div>
			</div>
		</div>
	</div>
</div>

app/views/tasks/show.html.erb
<% provide(:title, "Szczegóły zgłoszenia serwisowego nr: #{@task.id}" ) %>
<div class="container-fluid">


	<div class="row-fluid">
		<div class="col-md-12">
			<ol class="breadcrumb">
			  <li><%= link_to "Lista zleceń", tasks_path %></li>
			  <li class="active">Szczegóły zlecenia o nr: <%= @task.id %></li>
			</ol>
		</div>
		<div class="col-md-2">
			<div class="panel panel-default">
				<div class="panel-heading">
		    		<h3 class="panel-title text-center">Menu:</h3>
		  		</div>
			  <div class="panel-body text-center">
				<p>
					<%= link_to authenticated_root_path, class: "btn btn-primary btn-block" do %>
						<span class="glyphicon glyphicon-home"></span> Strona Główna
					<% end %>
					<% if @task.lock != true %>
						<% if can? :update, Task %>
							 <%= link_to edit_task_path, class: "btn btn-block btn-warning" do %>
									<span class="glyphicon glyphicon-pencil"></span> Edycja
							 <% end %>
						<% end %>
					<% end %>
					<% if can? :destroy, Task %>
						<%= link_to task_path, method: :delete, class: "btn btn-block btn-danger" do %>
								<span class="glyphicon glyphicon-trash"></span> Usuń
						<% end %>
					<% end %>
					<% if @task.lock != true %>
						<% if can? :update, Item %>
							<%= link_to task_items_path(@task), class: "btn btn-block btn-success" do %>
								<span class="glyphicon glyphicon-plus"></span> Sprzęt
							<% end %>
						<% end %>
						<% if @task.user == nil %>
							<% if can? :update, Task %>
								<%= link_to clients_tasks_path, class: "btn btn-block btn-success" do %>
									<span class="glyphicon glyphicon-plus"></span> Klient
								<% end %>
							<% end %>
						<% else %>
							<% if can? :update, Task %>
								<%= link_to remove_client_tasks_path(@task, @task.user.id), class: "btn btn-block btn-danger" do %>
									<span class="glyphicon glyphicon-minus"></span> Klient
								<% end %>
							<% end %>
						<% end %>
					<% end %>
					<%= link_to tasks_path, class: "btn btn-block btn-primary" do %>
						<span class="glyphicon glyphicon-arrow-left"></span> Wróć do listy zgłoszeń
					<% end %>
				</p>
			  </div>
			</div>
		</div>
		<div class="col-md-7">
			<div class="panel panel-default">
				<div class="panel-heading">
		    		<h3 class="panel-title text-center">Szczegóły zgłoszenia serwisowego:</h3>
		  		</div>
			  <div class="panel-body">
			  	<% if can? :update, Task %>
			  		<%= timesup_showpage(@task.end_task) %>
			  		<%= did_client_fly_with_us(@task.user_id) %>
			  		<%= you_have_my_sword(@task.items) %>
			  	<% end %>
				<p>
					<strong>Opis zgłoszenia</strong><br />
					<%= @task.description %><br />
					<strong>Zgłoszenie utworzył:</strong> <%= @task.author %><br />
					<strong>Odpowiedzialny za zgłoszenie:</strong> <% if @task.responsible.nil? %> Brak <% else %><%= @task.responsible %><% end %>
						<hr />

					<strong>Termin realizacji: </strong><%= l @task.end_task, format: :long %><br />
					<strong>Status zlecenia: </strong><%= @task.status.name %><br />
					<strong>Typ zlecenia: </strong><%= @task.type.name %><br /><br />

					<% if can? :update, Task # Ukrycie notatki serwisowej przed klientem. %>
						<% if @task.note != nil %>
							<% if @task.note != "" %>
								<div class="col-md-12">
									<div class="panel panel-info">
										<div class="panel-heading">
								    		<h3 class="panel-title text-center">Notatka serwisowa:</h3>
								  		</div>
									  <div class="panel-body">
												<%= @task.note %>
									  </div>
									</div>
								</div>
							<% end %>
						<% end # koniec if @task.note != "" %>
					<% end # koniec if role client %>

				</p>
			  </div>
			</div>
		</div>
		<div class="col-md-3">
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title text-center">Informacje o kliencie:</h3>
				</div>
				<div class="panel-body">
					<% if @task.user != nil %>
						<strong>Nr klienta: </strong><%= @task.user.id %><br />
						<strong>Imię i nazwisko: </strong><%= @task.user.full_name %><br />
						<strong>E-Mail: </strong><%= @task.user.email %><br />
						<strong>Login: </strong><%= @task.user.username %><br />
					<% else %>
						<div class="well well-lg text-center danger">Aktualnie nie ma żadnego klienta przypisanego do zgłoszenia.</div>
					<% end %>
				</div><!-- end panel-body -->
			</div><!-- end panel panel-success -->
		</div><!-- end col-md-3 info klinet -->
	</div> <!-- /row -->
		
	<% if @task.items.count != 0 %>
	<div class="row-fluid">
		<div class="col-md-12">
		<div class="panel panel-default">
			 <div class="panel-heading">
			    <h3 class="panel-title text-center">Serwisowany sprzęt:</h3>
			  </div>
			  <div class="panel-body">
				<!-- Tabela z przypisanymi kartami sprzętów -->

				<p>
					<div class="table-responsive">
						<table class="table table-bordered text-center">
							<tr>
								<th>ID</th>
								<th>Typ sprzętu</th>
								<th>Producent</th>
								<th>Model sprzętu</th>
								<th>Numer seryjny</th>
								<th>Data zakupu</th>
								<% if can? :update, Item %>
								<th>Utworzono</th>
								<th>Zmodyfikowano</th>
								<% end %>
								<th>Akcje</th>
							</tr>
						  <% @task.items.each do |item| %>
							<tr>
						                <td><%= link_to item.id, [@task,item] %></td>
						                <td><%= item.item_type %></td>
						                <td><%= item.item_producer %></td>
						                <td><%= item.item_model %></td>
						                <td><%= item.serial_number %></td>
						                <td><%= l item.purchase_date, format: :long %></td>
						                <% if can? :update, Item %>
						                <td><%= l item.created_at, format: :long %></td>
						                <td><%= l item.updated_at, format: :long %></td>
						                <% end %>
						                <td>
						                	<%= link_to [@task, item], class: "btn btn-primary btn-sm" do %>
												<span class="glyphicon glyphicon-folder-open"></span>
											<% end %>
						                	<% if can? :update, Item %>
						                	<%= link_to edit_task_item_path(@task, item), class: "btn btn-warning btn-sm" do %>
												<span class="glyphicon glyphicon-pencil"></span>
											<% end %>
											<% check_if_item_ta(@task, item) %>
											<%= link_to task_remove_item_path(@task, item), method: :get, class: "btn btn-danger btn-sm" do %>
												<span class="glyphicon glyphicon-minus"></span>
											<% end %>
											<% end %>
						                </td>
							</tr>
						  <% end # koniec bloku %>
						</table>
					</div> <!-- /table-responzive -->
				</p>
			  </div> <!-- /panel-body -->
			</div> <!-- /panel panel-default -->
		</div> <!-- /col-md-12 -->
	</div> <!-- /row -->
	<% end %>
</div> <!-- /container -->