config/routes.rb
Sos::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  # Strona startowa
  devise_scope :user do
    authenticated :user do # jeśli zalogowany
     root :to => 'tasks#index', as: :authenticated_root
   end
   unauthenticated :user do #jeśli nie zalogowany
     root :to => 'devise/sessions#new', as: :unauthenticated_root
   end
  end

  # Linki do panelu administracyjnego
  namespace :admin do
    # get "home/index" # Strona główna panelu adminisracyjnego
    get "dashboard" => 'home#index', as: :dashboard # Strona główna panelu adminisracyjnego
    resources :users
    get 'users/:id/gen_password' => 'users#gen_new_pass', as: :new_password_gen
    resources :roles, only: [:index, :edit, :update]
    get "logs" => 'logs#list', as: :logs #Logi
  end

  resources :tasks do
   resources :items

   # Odepnij sprzęt od zlecenia
   get 'items/:id/remove_from_task' => 'items#remove_from_task', as: :remove_item

   # Przypnij sprzęt do zlecenia
   get 'items/:id/add_to_task' => 'items#add_to_task', as: :add_item

   # Lista klientów do możliwych do dodania do zgłoszenia
   get '/:id/clients' => 'users#clients_list_to_task', as: :clients, on: :collection
   get '/:task_id/client/new' => 'users#new_client_to_task', as: :new_client, on: :collection
   get '/:task_id/clients/:id/add_to_task' => 'users#add_to_task', as: :add_client, on: :collection
   get '/:task_id/clients/:id/remove_from_task' => 'users#remove_from_task', as: :remove_client, on: :collection
   post '/clients' => 'users#create_task_client'
  end

  get 'archive' => 'tasks#archive', as: :archive

  resources :users

  # linki do klientów, zwenętrznej
  get 'clients' => 'users#clients', as: :clients_list
  get 'client/new' => 'users#new_client', as: :client_new
  post 'users/create_client'
  get 'client/:id' => 'users#show_client', as: :show_client
  get 'client/:id/edit' => 'users#edit', as: :edit_client
  delete 'client/:id' => 'users#destroy', as: :del_client
  put 'client/:id' => 'users#update'
  patch 'client/:id' => 'users#update' 
  get 'clients/:id/new/password' => 'users#pass_restart', as: :password_gen

  # linki do sprzętów, zwenętrznej
  get 'items' => 'items#items_list', as: :items_list
  get 'item/new' => 'items#item_new', as: :item_new
  post 'items/item_create'
  get 'item/:id' => 'items#item_show', as: :show_item
  get 'item/:id/edit' => 'items#item_edit', as: :edit_item
  delete 'item/delete/:id' => 'items#item_destroy', as: :del_item
  put 'item/:id/update' => 'items#item_update'
  patch 'item/:id/update' => 'items#item_update' 

  # Linki zarządzające profilem użytkownika
  get 'profile/:id' => 'users#profile', as: :profile
  get 'profile/:id/edit' => 'users#edit_profile', as: :profile_edit
  get 'profile/:id/password' => 'users#change_password', as: :profile_password
  put 'profile/:id' => 'users#profile_update'  # update profilu
  patch 'profile/:id' => 'users#profile_update' # update profilu
  put 'profile/:id/password' => 'users#password_update' # zmiana hasła
  patch 'profile/:id/password' => 'users#password_update' # zmiana hasła

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :tasks
  belongs_to :role

  attr_accessor :login
  after_create :set_default_role
  #after_create :generate_username
  # after_create :set_first_user_as_admin

  # Include default devise modules. Others available are:
  # :confirmable, :lockable and :omniauthable  :registerable, 
  devise :database_authenticatable, :rememberable, :recoverable, :trackable, :validatable, :timeoutable


  validates :username, :uniqueness => { :case_sensitive => false }
  validates  :full_name, presence: true

    def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end

    # generowanie nazwy uzytkonika
    def generate_username
      name_lowcase = self.full_name.downcase #Wszystkie literki zmień na małe
      name_ws = name_lowcase.gsub(/\s+/, "") #usuwanie spacji
      number = User.last.id #Pobierz id ostatniego użytkownika
      number += 1 #incnrement id
      name = "#{name_ws}#{number}"
      return name
    end

private
  # Ustaw domyślną rolę dla nowo zarejestrowanego użytkownika.
  def set_default_role
    user_to_role = User.find(self.id) # Znajdź nowego użytkownika zaraz po utworzeniu użytkownika
    if user_to_role.id != 1
      user_to_role.role_id = 4 # Przypisz mu aktomatycznie rolę klienta
      user_to_role.save
    else
      user_to_role.role_id = 1 # Przypisz mu aktomatycznie rolę klienta
      user_to_role.save
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

	before_action :find_user, only: [:show, :edit, :update, :destroy]
	authorize_resource :except => [:gen_new_pass]
  def index
    # admin/users
    @users = User.paginate(:page => params[:page], :per_page => 10).order(created_at: :asc)
  end

  def show
  end

  def edit 
  end

  def update
  	@user.update(user_params)
  		if @user.save
  			redirect_to admin_user_path, notice: "Użytkownik został prawidłowo zaktualizowany!"
        new_log("Zaktualizowano profil użytkownika o id: #{@user.id}, loginie #{@user.username}.", "Użytkownicy")
      else
        render "edit"
      end
  end

  def new
    @user = User.new
  end

  def create
      @user = User.new(user_params)
      @user.username = @user.generate_username
      generated_password = Devise.friendly_token.first(8)
      @user.password = generated_password
      if @user.save
        UserMailer.welcome(@user, generated_password).deliver
        redirect_to admin_users_path, notice: "Utworzono nowego prawidłowo użytkownika!"
        new_log("Utworzono nowego użytkownika o id: #{@user.id}, loginie #{@user.username}.", "Użytkownicy")
      else
        render "new"
      end
  end

  def gen_new_pass
    # generowanie nowego hasła
    @user = User.find(params[:id])
    generated_password = Devise.friendly_token.first(8)
    @user.password = generated_password

    if @user.save
        UserMailer.new_password(@user, generated_password).deliver
        redirect_to admin_users_path, notice: "Zrestartowano hasło użytkownika!"
        new_log("Zrestartowano hasło użytkownika o id: #{@user.id}, loginie #{@user.username}.", "Użytkownicy")
      else
        render "index", alert: "Nie udało się zrestartować hasła użytkownikowi"
      end
  end

  def destroy
    UserMailer.destroyed(@user).deliver
    new_log("Usunięto użytkownika z bazy danych o id: #{@user.id}.", "Użytkownicy")
    @user.destroy
    redirect_to admin_users_path, notice: "Użytkownik został poprawnie usunięty."
  end

  private

    def user_params
    	params.require(:user).permit(:user_id, :password, :username, :email, :full_name, :street, :city, :zip_code, :telephone, :nip, :note, :role_id)
    end

    def find_user
    	@user = User.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!
  authorize_resource :except => [:profile, :edit_profile, :profile_update, :change_password, :clients, :new_client, :show_client, :clients_list_to_task, :create_client, :add_to_task, :remove_from_task, :create_task_client, :new_client_to_task, :password_update, :pass_restart]

  def profile
    # Wyświetlanie profilu użytkownika
    @user = User.find(params[:id])
    authorize! :read, :profile
  end

  def pass_restart
    # resetowanie hasła
    @user = User.find(params[:id])
    generated_password = Devise.friendly_token.first(8)
    @user.password = generated_password

    if @user.save
        UserMailer.new_password(@user, generated_password).deliver
        redirect_to authenticated_root_path, notice: "Zrestartowano hasło użytkownika!"
        new_log("Zrestartowano hasło użytkownika o id: #{@user.id}, loginie #{@user.username}.", "Klientci")
      else
        render "clients", alert: "Nie udało się zrestartować hasła użytkownikowi"
      end
      authorize! :update, :pass
  end

  def profile_update
    @client = User.find(params[:id])
    @client.update(client_params)
    respond_to do |format|
      if @client.save
          format.html { redirect_to profile_path, notice: "Twoje dane zostały poprawnie zaktualizowane." }
          format.json { render action: 'profile', status: :created, location: @client }
          new_log("Klient o loginie: #{@client.username}, zaktualizował swój profil.", "Klienci - Profil")
      else
        format.html { render action: 'edit_profile' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
    authorize! :update, :profile
  end

  def password_update
    @client = User.find(params[:id])
    @client.update(client_password)
    respond_to do |format|
      if @client.save
          format.html { redirect_to profile_path, notice: "Twoje hasło zostało zmienione." }
          format.json { render action: 'profile', status: :created, location: @client }
          new_log("Klient o loginie: #{@client.username}, zmienił swoje hasło.", "Klienci - Profil")
      else
        format.html { render action: 'change_password' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
  end
    authorize! :update, :profile
  end

  def edit_profile
    @client = User.find(params[:id])
    authorize! :update, :edit
  end

  def change_password
    @client = User.find(params[:id])
    authorize! :update, :edit
  end

  def clients
    # Lista użytkowników z rolą klient
    @clients = User.paginate(:page => params[:page], :per_page => 10).where('role_id = ?', 4)
    authorize! :read, :clients
  end

  def clients_list_to_task
    @task = Task.find(params[:id])
    @clients = User.paginate(:page => params[:page], :per_page => 10).where('role_id = ?', 4)
    authorize! :update, :clients
  end

  def new_client
    @client = User.new
    authorize! :create, :clients
  end

  def new_client_to_task
    @task = Task.find(params[:task_id])
    @client = User.new
    authorize! :create, :clients
  end

  def show_client
    @client = User.find(params[:id])
    authorize! :read, :clients
  end

  def create_client
    @client = User.new(user_params)
    @client.username = @client.generate_username
    generated_password = Devise.friendly_token.first(8)
    @client.password = generated_password
    new_log("Utworzono nowego klienta o id: #{@client.id}, loginie: #{@client.username}", "Klienci")

    if @client.save
      UserMailer.welcome(@client, generated_password).deliver
      redirect_to clients_list_path, notice: "Utworzono prawidłowo nowego klienta o id: #{@client.id}!"
    else
      render "new_client"
    end
    authorize! :create, :clients
  end

  def create_task_client
    @task = Task.find(params[:task_id])
    @client = User.new(user_params)
    @client.username = @client.generate_username
    generated_password = Devise.friendly_token.first(8)
    @client.password = generated_password

    if @client.save
        @task.user_id = @client.id
        @task.save
        UserMailer.welcome(@client, generated_password).deliver
        redirect_to task_items_path(@task), notice: "Utworzono prawidłowo klienta o id: #{@client.id}, oraz przypisano go do zgłoszenia o id; #{@task.id}."
        new_log("Utworzono nowego klienta o id: #{@client.id}, loginie #{@client.username}, oraz przypisano go do zgłoszenia o id: #{@task.id}", "Klienci")
      else
        render "new_client_to_task"
      end
    authorize! :create, :clients
  end

  def edit
    @client = User.find(params[:id])
  end

  def update
    @client = User.find(params[:id])
    @client.update(user_params)
    respond_to do |format|
      if @client.save
          format.html { redirect_to show_client_path(@client), notice: "Dane klienta zostały poprawnie zaktualizowane!" }
          format.json { render action: 'clients', status: :created, location: @client }
          new_log("Zaktializowano dane klientna: #{@client.id}, loginie: #{@client.username}", "Klienci")
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @client = User.find(params[:id])
    new_log("Usunięto z systemu klienta o id: #{@client.id}", "Użytkownicy")
    @client.destroy
    respond_to do |format|
  
    UserMailer.destroyed(@client).deliver
    format.html { redirect_to clients_list_path, notice: "Klient został poprawnie usunięty z serwisu." }
    format.json { render action: 'clients', status: :created, location: @client }
  end
  end

  def add_to_task
    @client = User.find(params[:id])
    @task = Task.find(params[:task_id])

    if @task.user.nil?
      @task.user_id = @client.id
      @task.save
      new_log("Przypięto klienta (id: #{@client.id}) do zgłoszenia (id: #{@task.id})", "Klienci")
      redirect_to task_items_path(@task), notice: "Przypięto klienta o numerze: #{@client.id}, do zgłoszenia o id #{@task.id}."
    else
      redirect_to @task, alert: "Nie można już podpiąć kolejnego klienta do tego samego zgłoszenia!"
    end
    authorize! :update, :clients
  end

  def remove_from_task
    @client = User.find(params[:id])
    @task = Task.find(params[:task_id])
    @task.user_id = nil
     if @task.user_id.nil?
      new_log("Odepnięto klienta od zgłoszenia id: #{@task.id} ", "Klientci")
      @task.save
      redirect_to @task, notice: "Odpięto klienta #{@client.username} od tego zgłoszenia."
    end
    authorize! :update, :clients
  end

    def create
      @user = User.new(user_params)
      @user.username = @user.generate_username
      generated_password = Devise.friendly_token.first(8)
      @user.password = generated_password
      if @user.save
        UserMailer.welcome(@user, generated_password).deliver
        redirect_to admin_users_path, notice: "Utworzono nowego prawidłowo użytkownika!"
        new_log("Utworzono nowego użytkownika o id: #{@user.id}, loginie #{@user.username}.", "Użytkownicy")
      else
        render "new"
      end
  end

private

  def user_params
    params.require(:user).permit(:user_id, :password, :username, :email, :full_name, :street, :city, :zip_code, :telephone, :nip, :note, :role_id)
  end

  def client_params
    params.require(:user).permit(:user_id, :email, :full_name, :street, :city, :zip_code, :telephone, :nip)
  end

  def client_password
    params.require(:user).permit(:password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/change_password.html.erb
<% provide(:title, 'Zmiana hasła') %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-md-12">

			<ol class="breadcrumb">
			 	<li><%= link_to "Strona główna", tasks_path %></li>
			 	<li><%= link_to "Profil użytkownika", profile_path %></li>
			 	<li class="active">Edycja hasła użytkownika: <%= @client.username %></li>
			</ol>
		</div>
	</div>
	<div class="row-fluid">
		<div class="col-md-2">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title text-center">Menu</h3>
				</div>
				<div class="panel-body">
					<%= link_to authenticated_root_path, class: "btn btn-primary btn-block" do %>
						<span class="glyphicon glyphicon-home"></span> Strona Główna
					<% end %>
					<%= link_to profile_path, class: "btn btn-primary btn-block" do %>
						<span class="glyphicon glyphicon-arrow-left"></span> Wróć do profilu
					<% end %>
				</div>
			</div>
		</div>

			<div class="col-md-10">
			<div class="panel panel-default">
				<div class="panel-heading">
		    		<h3 class="panel-title text-center">Formularz edycji hasła klienta:</h3>
		  		</div>
			  <div class="panel-body">
				<div class="well well-lg text-center">
					Poniżej znajduje się formularz zmiany hasła użytkownika.
				</div>

				<%= render 'password_change_form' %>
				
			  </div>
			  <div class="panel-footer"></div>
			</div>

		</div>
	</div>
</div>

app/views/users/clients.html.erb
<% provide(:title, 'Lista klientów') %>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-md-2">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title text-center">Menu</h3>
				</div>
				<div class="panel-body">
					<%= link_to authenticated_root_path, class: "btn btn-primary btn-block" do %>
						<span class="glyphicon glyphicon-home"></span> Strona Główna
					<% end %>
					<% if can? :create, User %>
						<%= link_to client_new_path, class: "btn btn-primary btn-block" do %>
							<span class="glyphicon glyphicon-plus"></span> Utwórz nowego klienta
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
		<div class="col-md-10">
			
			<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title text-center">Liska klinetów</h3>
					</div>
					<div class="panel-body">
						<div class="well well-lg text-center">
							Poniżej znajduje się lista wszystkich klientów zarejestrowanych w serwisie. Możesz <strong>utworzyć nowego</strong> klienta lub <strong>zarządzać</strong> już istniejącymi.
						</div>
						<% if User.where('role_id = ?', 4).count > 0 %>
						<table class="table table-bordered text-center">
							<tr>
								<th>#</th>
								<th>Login</th>
								<th>Imię i nazwisko / Nazwa</th>
								<th>E-mail</th>
								<th>Akcje</th>
							</tr>
							<% @clients.each do |c| %>
							<tr>
								<td><%= link_to c.id, show_client_path(c) %></td>
								<td><%= c.username %></td>
								<td><%= c.full_name %></td>
								<td><%= c.email %></td>
								<td>
									<% if can? :read, User %>
										<%= link_to show_client_path(c), class: "btn btn-sm btn-primary" do %>
											<i class="fa fa-folder-open"></i>
										<% end %>
									<% end %>
									<% if can? :update, User %>
										<%= link_to edit_client_path(c), class: "btn btn-sm btn-warning" do %>
												<span class="glyphicon glyphicon-pencil"></span>
										<% end %>
							  		<% end %>
							  		<% if can? :destroy, User %>
										<%= link_to del_client_path(c), method: :delete,data: { confirm: "Czy na pewno chcesz usunąć tego klienta?"}, class: "btn btn-sm btn-danger" do %>
											<span class="glyphicon glyphicon-trash"></span>
										<% end %>
		  							<% end %>
		  							<% if can? :update, User %>
									 <%= link_to password_gen_path(c), class: "btn btn-success btn-sm" do %>
											<i class="fa fa-refresh"></i>
									 <% end %>
								<% end %>
								</td>
							</tr>
							<% end # koniec bloku%>
						</table>
						<% else %>
							<div class="well well-lg text-center">Aktualnie nie ma żadnych klientów zarejestrowanych w serwisie.</div>
						<% end %>
					</div>
					<div class="panel-footer"></div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/clients_list_to_task.html.erb
<% provide(:title, 'Lista klientów') %>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-md-2">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title text-center">Menu</h3>
				</div>
				<div class="panel-body">
					<%= link_to authenticated_root_path, class: "btn btn-primary btn-block" do %>
						<span class="glyphicon glyphicon-home"></span> Strona Główna
					<% end %>
					<% if can? :create, User %>
						<%= link_to new_client_tasks_path(@task), class: "btn btn-primary btn-block" do %>
							<span class="glyphicon glyphicon-plus"></span> Utwórz klienta
						<% end %>
					<% end %>
					<%= link_to task_path(@task), class: "btn btn-primary btn-block" do %>
							<span class="glyphicon glyphicon-arrow-left"></span> Wróc do zgłoszenia
					<% end %>
				</div>
			</div>
		</div>
		<div class="col-md-10">
			
			<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title text-center">Liska klinetów</h3>
					</div>
					<div class="panel-body">
						<div class="well well-lg text-center">
							Poniżej znajduje się lista wszystkich klientów zarejestrowanych w serwisie. Możesz <strong>utworzyć nowego</strong> klienta lub <strong>dodać</strong> już istniejącego. Niezależnie od wyboru klient zostanie <strong>przypięty</strong> do zgłoszenia serwisowego.
						</div>
						<% if User.where('role_id = ?', 4).count > 0 %>
						<table class="table table-bordered text-center">
							<tr>
								<th>#</th>
								<th>Login</th>
								<th>Imię i nazwisko / Nazwa</th>
								<th>E-mail</th>
								<th>Akcje</th>
							</tr>
							<% @clients.each do |c| %>
							<tr>
								<td><%= link_to c.id, show_client_path(c) %></td>
								<td><%= c.username %></td>
								<td><%= c.full_name %></td>
								<td><%= c.email %></td>
								<td>
									<% if can? :read, User %>
										<%= link_to show_client_path(c), class: "btn btn-sm btn-primary" do %>
											<i class="fa fa-folder-open"></i>
										<% end %>
									<% end %>
		  							<% if can? :update, User %>
											<%= link_to add_client_tasks_path(@task, c), method: :get, class: "btn btn-success btn-sm" do %>
													<span class="glyphicon glyphicon-plus"></span>
											<% end %>
									<% end %>
								</td>
							</tr>
							<% end # koniec bloku%>
						</table>
						<% else %>
							<div class="well well-lg text-center">Aktualnie nie ma żadnych klientów zarejestrowanych w serwisie.</div>
						<% end %>
					</div>
					<div class="panel-footer"></div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edycja konta klienta') %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-md-12">

			<ol class="breadcrumb">
			 	<li><%= link_to "Strona główna", tasks_path %></li>
			 	<li><%= link_to "Lista klientów", clients_list_path %></li>
			 	<li class="active">Edytuj klienta: <%= @client.username %></li>
			</ol>
		</div>
	</div>
	<div class="row-fluid">
		<div class="col-md-2">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title text-center">Menu</h3>
				</div>
				<div class="panel-body">
					<%= link_to authenticated_root_path, class: "btn btn-primary btn-block" do %>
						<span class="glyphicon glyphicon-home"></span> Strona Główna
					<% end %>
					<% if can? :read, User %>
						<%= link_to clients_list_path, class: "btn btn-primary btn-md btn-block"  do %>
							<span class="glyphicon glyphicon-arrow-left"></span> Wróć do listy klientów
						<% end %>
					<% end %>
				</div>
			</div>
		</div>

			<div class="col-md-10">
			<div class="panel panel-default">
				<div class="panel-heading">
		    		<h3 class="panel-title text-center">Formularz edycji danych klienta:</h3>
		  		</div>
			  <div class="panel-body">
				<div class="well well-lg text-center">
					Poniżej znajduje się formularz w którym można dokonać zmiany dancyh klienta serwisu.
				</div>

				<%= render 'client_update_form' %>
				
			  </div>
			  <div class="panel-footer"></div>
			</div>

		</div>
	</div>
</div>

app/views/users/new_client_to_task.html.erb
<% provide(:title, 'Dodaj nowego klienta') %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-md-12">

			<ol class="breadcrumb">
			 	<li><%= link_to "Strona główna", authenticated_root_path %></li>
			 	<li><%= link_to "Zgłoszenie nr #{@task.id}", task_path(@task) %></li>
			 	<li><%= link_to "Lista klientów", clients_tasks_path(@task) %></li>
			 	<li class="active">Utwórz nowego klienta</li>
			</ol>
		</div>
	</div>
	
		<div class="row-fluid">
		<div class="col-md-2">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title text-center">Menu</h3>
				</div>
				<div class="panel-body">
					<%= link_to authenticated_root_path, class: "btn btn-primary btn-block" do %>
						<span class="glyphicon glyphicon-home"></span> Strona Główna
					<% end %>
					<%= link_to clients_tasks_path(@task), class: "btn btn-primary btn-md btn-block"  do %>
						<span class="glyphicon glyphicon-arrow-left"></span> Wróć do listy klientów
					<% end %></%>
				</div>
			</div>
		</div>
		<div class="col-md-10">
			<div class="panel panel-default">
				<div class="panel-heading">
		    		<h3 class="panel-title text-center">Formularz nowego klienta:</h3>
		  		</div>
			  <div class="panel-body">
				<div class="well well-lg text-center">
					Wypełnij formularz z danymi nowego klienta serwisu. Po poporawyny wysłaniu formularza klient zostanie dodany do systemu oraz przypisany do zgłoszenia.
				</div>

				<%= render 'client_new_and_add_to_task' %>
			  </div>
			  <div class="panel-footer"></div>
			</div>

		</div>
	</div>
</div>

app/views/users/profile.html.erb
<% provide(:title, "Profil użytkownika" ) %>
<div class="container-fluid">

	<div class="row-fluid">
			<div class="col-md-12">
				<ol class="breadcrumb">
				  <li><%= link_to "Strona Główna", authenticated_root_path %></li>
				  <li class="active">Profil użytkownika</li>
				</ol>
			</div>
	</div> <!-- row -->
	<div class="row-fluid">
		<div class="col-md-2">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title text-center">Menu</h3>
				</div>
				<div class="panel-body">
					<%= link_to authenticated_root_path, class: "btn btn-primary btn-block" do %>
						<span class="glyphicon glyphicon-home"></span> Strona Główna
					<% end %>
				  	<%= link_to profile_edit_path(@user), class: "btn btn-warning btn-block" do %>
						<span class="glyphicon glyphicon-pencil"></span> Edytuj profil
					<% end %>
					<%= link_to profile_password_path(@user), class: "btn btn-warning btn-block" do %>
						<span class="glyphicon glyphicon-pencil"></span> Zmień hasło
					<% end %>
				</div>
			</div>
		</div>
		<div class="col-md-10">
		<div class="panel panel-default">
			<div class="panel-heading">
		   		<h3 class="panel-title text-center">Profil użytkownika</h3>
		  	</div>
		  <div class="panel-body">
		  	<p>
		  		<strong>Login:</strong> <%= current_user.username %><br />
		  		<strong>E-mail:</strong> <%= current_user.email %><br />
				<strong>Imię i nazwisko:</strong> <%= current_user.full_name %><br />
				<strong>Ulica:</strong> <%= current_user.street %><br />
				<strong>Miasto:</strong> <%= current_user.city %><br />
				<strong>Kod Pocztowy:</strong> <%= current_user.zip_code %><br />
				<strong>Telefon:</strong> <%= current_user.telephone %><br />
				<strong>NIP:</strong> <%= current_user.nip %><br />
				<strong>Ilość logowań do serwisu:</strong> <%= current_user.sign_in_count %><br />
				<strong>Zarejestrowany od:</strong> <%= l current_user.created_at, format: :long %>
		  	</p>
		  	<% if can? :create, User %>
			  	<% if current_user.note != nil %>
				  	<p>
				  		<strong>Notatka:</strong><%= current_user.note %>
				  	</p>
				<% end %>
			<% end %>
			</div>
		  </div>
		</div>
	</div>
</div> <!-- /container -->