config/routes.rb
Sos::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  # Strona startowa
  devise_scope :user do
    authenticated :user do # jeśli zalogowany
     root :to => 'tasks#index', as: :authenticated_root
   end
   unauthenticated :user do #jeśli nie zalogowany
     root :to => 'devise/sessions#new', as: :unauthenticated_root
   end
  end

  # Linki do panelu administracyjnego
  namespace :admin do
    # get "home/index" # Strona główna panelu adminisracyjnego
    get "dashboard" => 'home#index', as: :dashboard # Strona główna panelu adminisracyjnego
    resources :users
    get 'users/:id/gen_password' => 'users#gen_new_pass', as: :new_password_gen
    resources :roles, only: [:index, :edit, :update]
    get "logs" => 'logs#list', as: :logs #Logi
  end

  resources :tasks do
   resources :items

   # Odepnij sprzęt od zlecenia
   get 'items/:id/remove_from_task' => 'items#remove_from_task', as: :remove_item

   # Przypnij sprzęt do zlecenia
   get 'items/:id/add_to_task' => 'items#add_to_task', as: :add_item

   # Lista klientów do możliwych do dodania do zgłoszenia
   get '/:id/clients' => 'users#clients_list_to_task', as: :clients, on: :collection
   get '/:task_id/client/new' => 'users#new_client_to_task', as: :new_client, on: :collection
   get '/:task_id/clients/:id/add_to_task' => 'users#add_to_task', as: :add_client, on: :collection
   get '/:task_id/clients/:id/remove_from_task' => 'users#remove_from_task', as: :remove_client, on: :collection
   post '/clients' => 'users#create_task_client'
  end

  get 'archive' => 'tasks#archive', as: :archive

  resources :users

  # linki do klientów, zwenętrznej
  get 'clients' => 'users#clients', as: :clients_list
  get 'client/new' => 'users#new_client', as: :client_new
  post 'users/create_client'
  get 'client/:id' => 'users#show_client', as: :show_client
  get 'client/:id/edit' => 'users#edit', as: :edit_client
  delete 'client/:id' => 'users#destroy', as: :del_client
  put 'client/:id' => 'users#update'
  patch 'client/:id' => 'users#update' 
  get 'clients/:id/new/password' => 'users#pass_restart', as: :password_gen

  # linki do sprzętów, zwenętrznej
  get 'items' => 'items#items_list', as: :items_list
  get 'item/new' => 'items#item_new', as: :item_new
  post 'items/item_create'
  get 'item/:id' => 'items#item_show', as: :show_item
  get 'item/:id/edit' => 'items#item_edit', as: :edit_item
  delete 'item/delete/:id' => 'items#item_destroy', as: :del_item
  put 'item/:id/update' => 'items#item_update'
  patch 'item/:id/update' => 'items#item_update' 

  # Linki zarządzające profilem użytkownika
  get 'profile/:id' => 'users#profile', as: :profile
  get 'profile/:id/edit' => 'users#edit_profile', as: :profile_edit
  get 'profile/:id/password' => 'users#change_password', as: :profile_password
  put 'profile/:id' => 'users#profile_update'  # update profilu
  patch 'profile/:id' => 'users#profile_update' # update profilu
  put 'profile/:id/password' => 'users#password_update' # zmiana hasła
  patch 'profile/:id/password' => 'users#password_update' # zmiana hasła

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :cards
  has_many :tasks, :through => :cards

  validates  :item_type, presence: true
  validates  :item_producer, presence: true
  validates  :item_model, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :authenticate_user! 
  before_action :find_item, only: [:edit, :update, :destroy, :show]
  authorize_resource :except => [:remove_from_task, :add_to_task, :add_or_create, :show, :items_list, :item_new, :item_edit, :item_create, :item_destroy, :item_update, :item_show]

  def index
    @can_add = true
    @task = Task.find(params[:task_id])
  	@items = Item.paginate(:page => params[:page], :per_page => 10).order(created_at: :desc)
  end

  def items_list
    @items = Item.paginate(:page => params[:page], :per_page => 10).order(created_at: :desc)
    authorize! :read, :item
  end

  def item_new
    @item = Item.new
    authorize! :create, :item
  end

  def item_show
    @item = Item.find(params[:id])
    authorize! :read, :item
  end

  def item_edit
    @item = Item.find(params[:id])
    authorize! :update, :item
  end

  def item_create
    @item = Item.new(item_params)
    if @item.save
      redirect_to show_item_path(@item), notice: "Karta sprzętu została poprawnie utworzona!"
      new_log("Utworzono nową kartę sprzętu o numerze: #{@item.id} - [#{@item.item_producer}] [#{@item.item_model}]", "Karty sprzętu")
    else
      render "item_new"
    end
    authorize! :create, :item
  end

  def item_update
    @item = Item.find(params[:id])
    @item.update(item_params)
    if @item.save
      redirect_to items_list_path, notice: "Kartas sprzętu została zaktualizowana!"
      new_log("Zaktualizowano kartę sprzętu o id: #{@item.id} - [#{@item.item_producer}] [#{@item.item_model}]", "Karty sprzętu")
    end
    authorize! :update, :item
  end

  def item_destroy
    @item = Item.find(params[:id])
    new_log("Usunięto kartę sprzętu o numerze: #{@item.id} - [#{@item.item_producer}] [#{@item.item_model}]", "Karty sprzętu")
    @item.destroy
    if @item.save
      redirect_to items_list_path, notice: "Karta sprzętu została porawnie usunięta!"
    end
    authorize! :destroy, :item
  end

  def show
    @task = Task.find(params[:task_id])
    authorize! :read, :show_item
  end

  def new
    @task = Task.find(params[:task_id])
    @item = @task.items.build
  end

  def edit
    @task = Task.find(params[:task_id])
  end

  def create
    @task = Task.find(params[:task_id])
  	@item = @task.items.build(item_params)
  	if @item.save
      @task.items << @item
      # Jeśli będę chciał przekierować na Items#index to ścieżka: task_items_path
  		redirect_to task_items_path, notice: "Karta sprzętu o numerze: #{@item.id} została utworzona, oraz została poprawnie przypięta do zgłoszenia serwisowego o numerze: #{@task.id}!"
      new_log("Utworzono nową kartę sprzętu oraz przypisano ją do zgłoszenia", "Karty sprzętu")
  	else
  		render "new"
  	end
  end

  def destroy
  	@item = Item.find(params[:id])
    new_log("Usunięto kartę sprzętu o numerze: #{@item.id} - [#{@item.item_producer}] [#{@item.item_model}]", "Karty sprzętu")
    @item.destroy
    if @item.save
      redirect_to task_items_path, notice: "Karta sprzętu została porawnie usunięta!"
  	end
  end

  def update
    @task = Task.find(params[:task_id])
  	@item.update(item_params)
  	if @item.save
  		redirect_to task_item_path, notice: "Karta sprzętu została poprawnie zaktualizowana!"
      new_log("Zaktualizowano kartę sprzętu o id: #{@item.id} - [#{@item.item_producer}] [#{@item.item_model}]", "Karty sprzętu")
  	end
  end

  def add_or_create
    @items = Item.paginate(:page => params[:page], :per_page => 10).order(created_at: :desc)
    authorize! :update, :item
  end

  def add_to_task
    @item = Item.find(params[:id])
    @task = Task.find(params[:task_id])
    
    # Wyświetl tę zdefiniowana kartę sprzętu
    @a = @task.items.find_by_id(@item.id)

    # Czy karty sprzętu nie ma dołączonej do zgłoszenia ?
    if @a.nil? 
      @task.items << @item
      new_log("Przypięto sprzęt o numerze: #{@item.id} do zgłoszenia o id: #{@task.id}.", "Sprzęt")
      redirect_to task_items_path(@task), notice: "Przypięto sprzęt o numerze: #{@item.id}, do zgłoszenia."
    else
      redirect_to @task, alert: "Nie można podpiąć tego samego sprzętu do jednego zlecenia!"
    end
    authorize! :update, :item
  end

 # Jeśli jest kilka tych samych kart sprzętowych w zeceniu, wywołanie akcji usunie je wszystkie !
  def remove_from_task
    @task = Task.find(params[:task_id])
    @item = Item.find(params[:id])
    
     if @task.items.delete(@item)
      new_log("Odepnięto sprzęt o numerze: #{@item.id} od zgłoszenia o id: #{@task.id}.", "Sprzęt")
      redirect_to task_items_path(@task), notice: "Odpięto sprzęt o numerze: #{@item.id} od zgłoszenia."
    end
    authorize! :update, :item
  end

  private

  def item_params
  	params.require(:item).permit(:item_type, :item_producer, :item_model, :serial_number, :purchase_date, :note, :description, :task_id, :used)
  end

  def find_item
    @item = Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper

	def check_if_item_ta(task, one_item)
		a = task.items.find_by_id(one_item.id)
		if a.nil?
			@can_add = true
		else
			@can_add = false
		end

	end
	
end

app/views/items/edit.html.erb
<% provide(:title, 'Edycja danych karty sprzętu') %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-md-12">

			<ol class="breadcrumb">
			 	<li><%= link_to "Strona główna", authenticated_root_path%></li>
			 	<li><%= link_to "Zgłoszenie nr #{@task.id}", task_path(@task) %></li>
			 	<li><%= link_to "Lista kart sprzętów", task_items_path(@task) %></li>
			 	<li class="active">Edytuj kartę sprzętu o id: <%= @item.id %> - <%= @item.item_producer %> - <%= @item.item_model %></li>
			</ol>
		</div>
	</div>
	
		<div class="row-fluid">
		<div class="col-md-2">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title text-center">Menu</h3>
				</div>
				<div class="panel-body">
					<%= link_to authenticated_root_path, class: "btn btn-primary btn-block" do %>
						<span class="glyphicon glyphicon-home"></span> Strona Główna
					<% end %>
					<%= link_to task_items_path(@task), class: "btn btn-primary btn-md btn-block"  do %>
						<span class="glyphicon glyphicon-arrow-left"></span> Wróć do listy k. sprzętów
					<% end %></%>
				</div>
			</div>
		</div>
		<div class="col-md-10">
			<div class="panel panel-default">
				<div class="panel-heading">
		    		<h3 class="panel-title text-center">Formularz edycji karty sprzętu:</h3>
		  		</div>
			  <div class="panel-body">
				<div class="well well-lg text-center">
					Poniżej znajduje się formularz edycji karty sprzętu o numerze: <%= @item.id %>. Wprowadź nowe dane i wyślij formularz w celu zaktualizowania danych.
				</div>

				<%= render 'item_form' %>
			  </div>
			  <div class="panel-footer"></div>
			</div>

		</div>
	</div>
</div>

app/views/items/index.html.erb
<% provide(:title, "Lista sprzętów" ) %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-md-12">
			<ol class="breadcrumb">
			  <li><%= link_to "Lista zgłoszeń serwisowych", tasks_path %></li>
			  <li><%= link_to "Szczegóły zgłoszenia nr #{@task.id}", task_path(@task) %></li>
			  <li class="active">Lista kart sprzętu</li>
			</ol>
		</div>
	</div>
	<div class="row-fluid">
		<div class="col-md-2">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title text-center">Menu</h3>
				</div>
				<div class="panel-body">
					<%= link_to authenticated_root_path, class: "btn btn-primary btn-block" do %>
						<span class="glyphicon glyphicon-home"></span> Strona Główna
					<% end %>
					<% if can? :create, Item %>
						<%= link_to new_task_item_path, class: "btn btn-primary btn-block" do %>
							<span class="glyphicon glyphicon-plus"></span> Utwórz nową k. sprzętu
						<% end %>
					<% end %>
					<%= link_to task_path(@task), class: "btn btn-success btn-block" do %>
						<span class="glyphicon glyphicon-arrow-left"></span> Wróć do zgłoszenia
					<% end %>
				</div>
			</div>
		</div>
		<div class="col-md-10">
			<div class="panel panel-default">
				<div class="panel-heading text-center"><h2 class="panel-title">Lista kart sprzętów</h2></div>
				<div class="panel-body">
						<div class="well well-lg text-center">
							Poniżej znajduje się lista wszystkich kart sprzętów dostępnych w serwisie. Możesz <strong>utworzyć nową</strong> kartę sprzętu lub <strong>dodać</strong> już istniejące. Po <strong>dodaniu</strong> kart sprzętu można zakończyć proces kreowania zgłoszenia klikając w bocznym menu na przycisk <strong><i>Wróć do zgłoszenia</i></strong>.
						</div>
					<% if @items.count > 0 %>
					<div class="table-responsive">
					<table class="table table-bordered text-center">

						<tr>
							<th>ID</th>
							<th>Typ sprzętu</th>
							<th>Producent</th>
							<th>Model sprzętu</th>
							<th>Numer seryjny</th>
							<th>Data zakupu</th>
							<th>Utworzono</th>
							<th>Akcje</th>
						</tr>
					  <% @items.each do |item| %>
						<tr>
					                <td><%= link_to item.id, [@task, item] %></td>
					                <td><%= item.item_type %></td>
					                <td><%= item.item_producer %></td>
					                <td><%= item.item_model %></td>
					                <td><%= item.serial_number %></td>
					                <td><%= item.purchase_date %></td>
					                <td><%= l item.created_at, format: :long %></td>
					                <td>
					                	<% if can? :read, Item %>
					                		<%= link_to [@task, item], class: "btn btn-primary btn-sm" do %>
												<span class="glyphicon glyphicon-folder-open"></span>
					                		<% end %>
					                	<% end %>
					                	<% if can? :update, Item %>
						                	<%= link_to edit_task_item_path(@task, item), class: "btn btn-warning btn-sm" do %>
						                		<span class="glyphicon glyphicon-pencil"></span>
						                	<% end %>
					                	<% end %>
					                	<% if can? :destroy, Item %>
						                	<%= link_to [@task, item], method: :delete, data: { confirm: "Czy na pewno chcesz usunąć tą kartę sprzętu?"}, class: "btn btn-danger btn-sm" do %>
						                		<span class="glyphicon glyphicon-trash"></span>
											<% end %>
										<% end %>
									<% check_if_item_ta(@task, item) %> <!-- helper do sprawdzenia czy sprzęt jest już dodany do zgłoszenia -->
											<% if @can_add == true %>
												<% if can? :update, Item %>
													<%= link_to task_add_item_path(@task, item), method: :get, class: "btn btn-success btn-sm" do %>
															<span class="glyphicon glyphicon-plus"></span>
													<% end %>
												<% end %>
											<% else %>
												<% if can? :update, Item %>
													<%= link_to task_remove_item_path(@task, item), method: :get, class: "btn btn-danger btn-sm" do %>
															<span class="glyphicon glyphicon-minus"></span>
													<% end %>
												<% end %>
											<% end %>
					                </td>						
						</tr>
					  <% end %>
					</table>
				</div> <!-- end table-responsive -->
				<% else %>
				<div class="well well-lg text-center">Aktualnie nie ma żadnych utworzonych kart sprzętów</div>
					<% end # koniec if %>
				</div> <!-- end panel - body -->
				<div class="panel-footer">
					<div class="text-center">
						<%= will_paginate @tasks %>
					</div>
				</div>
			</div> <!-- end panel -->
		</div>
	</div>
</div>

app/views/items/item_show.html.erb
<% provide(:title, "Szczegóły sprzętu nr: #{@item.id}" ) %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-md-12">

			<ol class="breadcrumb">
			 	<li><%= link_to "Strona główna", authenticated_root_path%></li>
			 	<li><%= link_to "Lista kart sprzętów", items_list_path %></li>
			  <li class="active">Szczegóły sprzętu: [<%= @item.item_producer %> <%= @item.item_model %>] - numer sprzętu: <%= @item.id %></li>
			</ol>
		</div>
		<div class="row-fluid">

			<div class="col-md-2">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title text-center">Menu:</h3>
					</div>
					<div class="panel-body">
						<%= link_to authenticated_root_path, class: "btn btn-primary btn-block" do %>
							<span class="glyphicon glyphicon-home"></span> Strona Główna
						<% end %>
						<% if can? :update, Item %>
							<%= link_to edit_item_path(@item), class: "btn btn-block btn-warning" do %>
								<span class="glyphicon glyphicon-pencil"></span> Edytuj sprzęt
							<% end %>
						<% end %>

						<% if can? :destroy, Item %>
							<%= link_to del_item_path(@item), method: :delete, data: {confirm: "Czy na pewno chcesz usunąć ten sprzęt ?"}, class: "btn btn-danger btn-block" do %>
								<span class="glyphicon glyphicon-trash"></span> Usuń sprzęt
							<% end %>
						<% end %>
						<% if can? :create, Item %>
							<%= link_to item_new_path, class: "btn btn-primary btn-block" do %>
								<span class="glyphicon glyphicon-plus"></span> Stwórz nowy sprzęt
							<% end %>
						<% end %>
							<%= link_to items_list_path(@item), class: "btn btn-primary btn-block" do %>
								<span class="glyphicon glyphicon-arrow-left"></span> Wróć do listy sprzętów
							<% end %>

					</div><!-- end panel-body -->
				</div><!-- end panel -->
			</div>
			<div class="col-md-10">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title text-center">Szczegóły sprzętu:</h3>
					</div>
					<div class="panel-body">

						<table class="table table-bordered text-center">
							<tr>
								<th><strong>Typ spzętu:</strong></th>
								<td><%= @item.item_type %></td>
							</tr>
							<tr>
								<th><strong>Producent:</strong></th>
								<td><%= @item.item_producer %></td>
							</tr>
							<tr>
								<th><strong>Model:</strong></th>
								<td><%= @item.item_model %></td>
							</tr>
							<tr>
								<th><strong>Numer seryjny:</strong></th>
								<td><%= @item.serial_number %></td>
							</tr>
							<tr>
								<th><strong>Opis sprzętu:</strong></th>
								<td><%= @item.description %></td>
							</tr>
							<tr>
								<th><strong>Data zakupu:</strong></th>
								<td><%= l @item.purchase_date, format: :long %></td>
							</tr>
							<% if @item.used != true %>
							<tr>
								<th><strong>Koniec gwaracji:</strong></th>
								<td><%= l @item.purchase_date + 365.days, format: :long %></td>
							</tr>
							<% end %>
							<tr>
								<th><strong>Notatka serwisowa:</strong></th>
								<td>
									<% if !@item.note.empty? %>
										<%= @item.note %>
									<% else %>
										Brak notatki serwisowej.
									<% end %>
								</td>
							</tr>
							<tr>
								<th><strong>Utworzenie karty sprzętu:</strong></th>
								<td><%= l @item.created_at, format: :long %></td>
							</tr>
							<tr>
								<th><strong>Modyfikacja karty sprzętu:</strong></th>
								<td><%= l @item.updated_at, format: :long %></td>
							</tr>
						</table>
					</div><!-- end panel-body -->
				</div><!-- end panel -->
			</div> <!-- end col-md-9 -->
		</div><!-- end col-md-12 -->
	</div><!-- end row -->
</div><!-- end container -->

app/views/items/items_list.html.erb
<% provide(:title, "Lista sprzętów" ) %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-md-2">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title text-center">Menu</h3>
				</div>
				<div class="panel-body">
					<%= link_to authenticated_root_path, class: "btn btn-primary btn-block" do %>
						<span class="glyphicon glyphicon-home"></span> Strona Główna
					<% end %>
					<% if can? :create, Item %>
						<%= link_to item_new_path, class: "btn btn-primary btn-block" do %>
							<span class="glyphicon glyphicon-plus"></span> Utwórz nową k. sprzętu
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
		<div class="col-md-10">
			<div class="panel panel-default">
				<div class="panel-heading text-center"><h2 class="panel-title">Lista kart sprzętów</h2></div>
				<div class="panel-body">
						<div class="well well-lg text-center">
							Poniżej znajduje się lista wszystkich kart sprzętów dostępnych w serwisie. Możesz <strong>utworzyć nową</strong> kartę sprzętu lub <strong>zarządzać</strong> już istniejącymi kartami.
						</div>
					<% if @items.count > 0 %>
					<div class="table-responsive">
					<table class="table table-bordered text-center">

						<tr>
							<th>ID</th>
							<th>Typ sprzętu</th>
							<th>Producent</th>
							<th>Model sprzętu</th>
							<th>Numer seryjny</th>
							<th>Data zakupu</th>
							<th>Utworzono</th>
							<th>Akcje</th>
						</tr>
					  <% @items.each do |item| %>
						<tr>
					                <td><%= link_to item.id, show_item_path(item) %></td>
					                <td><%= item.item_type %></td>
					                <td><%= item.item_producer %></td>
					                <td><%= item.item_model %></td>
					                <td><%= item.serial_number %></td>
					                <td><%= item.purchase_date %></td>
					                <td><%= l item.created_at, format: :long %></td>
					                <td>
					                	<% if can? :read, Item %>
					                		<%= link_to show_item_path(item), class: "btn btn-primary btn-sm" do %>
												<span class="glyphicon glyphicon-folder-open"></span>
					                		<% end %>
					                	<% end %>
					                	<% if can? :update, Item %>
						                	<%= link_to edit_item_path(item), class: "btn btn-warning btn-sm" do %>
						                		<span class="glyphicon glyphicon-pencil"></span>
						                	<% end %>
					                	<% end %>
					                	<% if can? :destroy, Item %>

						                	<%= link_to del_item_path(item), method: :delete, action: "item_delstroy", data: { confirm: "Czy na pewno chcesz usunąć tą kartę sprzętu?"}, class: "btn btn-danger btn-sm" do %>
						                		<span class="glyphicon glyphicon-trash"></span>
											<% end %>
										<% end %>
					                </td>						
						</tr>
					  <% end %>
					</table>
				</div> <!-- end table-responsive -->
				<% else %>
				<div class="well well-lg text-center">Aktualnie nie ma żadnych utworzonych kart sprzętów</div>
					<% end # koniec if %>
				</div> <!-- end panel - body -->
				<div class="panel-footer">
					<div class="text-center">
						<%= will_paginate @tasks %>
					</div>
				</div>
			</div> <!-- end panel -->
		</div>
	</div>
</div>

app/views/items/show.html.erb
<% provide(:title, "Szczegóły sprzętu nr: #{@item.id}" ) %>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-md-12">

			<ol class="breadcrumb">
			  <li><%= link_to "Lista zleceń", tasks_path %></li>
			  <li><%= link_to "Szczegóły zgłoszenia nr #{@task.id}", task_path(@task) %></li>
			  <% if can? :update, Item %><li><%= link_to "Lista sprzętów", task_items_path(@task) %></li><% end %>
			  <li class="active">Szczegóły sprzętu: [<%= @item.item_producer %> <%= @item.item_model %>] - numer sprzętu: <%= @item.id %></li>
			</ol>
		</div>
		<div class="row-fluid">

			<div class="col-md-2">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title text-center">Menu:</h3>
					</div>
					<div class="panel-body">
						<%= link_to authenticated_root_path, class: "btn btn-primary btn-block" do %>
							<span class="glyphicon glyphicon-home"></span> Strona Główna
						<% end %>
						<% if can? :update, Item %>
							<%= link_to edit_task_item_path(@task,@item), class: "btn btn-block btn-warning" do %>
								<span class="glyphicon glyphicon-pencil"></span> Edytuj sprzęt
							<% end %>
						<% end %>

						<% if can? :destroy, Item %>
							<%= link_to [@task, @item], method: :delete, data: {confirm: "Czy na pewno chcesz usunąć ten sprzęt ?"}, class: "btn btn-danger btn-block" do %>
								<span class="glyphicon glyphicon-trash"></span> Usuń sprzęt
							<% end %>
						<% end %>
						<% if can? :update, Item %>
							<%= link_to task_items_path(@task), class: "btn btn-primary btn-block" do %>
								<span class="glyphicon glyphicon-arrow-left"></span> Wróć do listy sprzętów
							<% end %>
						<% else %>
							<%= link_to task_path(@task), class: "btn btn-primary btn-block" do %>
								<span class="glyphicon glyphicon-arrow-left"></span> Wróć do zgłoszenia
							<% end %>
						<% end %>

					</div><!-- end panel-body -->

				</div><!-- end panel -->
			</div>
			<div class="col-md-10">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title text-center">Szczegóły sprzętu:</h3>
					</div>
					<div class="panel-body">

						<table class="table table-bordered text-center">
							<tr>
								<th><strong>Typ spzętu:</strong></th>
								<td><%= @item.item_type %></td>
							</tr>
							<tr>
								<th><strong>Producent:</strong></th>
								<td><%= @item.item_producer %></td>
							</tr>
							<tr>
								<th><strong>Model:</strong></th>
								<td><%= @item.item_model %></td>
							</tr>
							<tr>
								<th><strong>Numer seryjny:</strong></th>
								<td><%= @item.serial_number %></td>
							</tr>
							<tr>
								<th><strong>Opis sprzętu:</strong></th>
								<td><%= @item.description %></td>
							</tr>
							<tr>
								<th><strong>Data zakupu:</strong></th>
								<td><%= l @item.purchase_date, format: :long %></td>
							</tr>
							<% if @item.used != true %>
							<tr>
								<th><strong>Koniec gwaracji:</strong></th>
								<td><%= l @item.purchase_date + 365.days, format: :long %></td>
							</tr>
							<% end %>
							<tr>
								<th><strong>Notatka serwisowa:</strong></th>
								<td>
									<% if !@item.note.empty? %>
										<%= @item.note %>
									<% else %>
										Brak notatki serwisowej.
									<% end %>
								</td>
							</tr>
							<tr>
								<th><strong>Utworzenie karty sprzętu:</strong></th>
								<td><%= l @item.created_at, format: :long %></td>
							</tr>
							<tr>
								<th><strong>Modyfikacja karty sprzętu:</strong></th>
								<td><%= l @item.updated_at, format: :long %></td>
							</tr>
						</table>
					</div><!-- end panel-body -->
				</div><!-- end panel -->
			</div> <!-- end col-md-9 -->
		</div><!-- end col-md-12 -->
	</div><!-- end row -->
</div><!-- end container -->