config/routes.rb
Sos::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  # Strona startowa
  devise_scope :user do
    authenticated :user do # jeśli zalogowany
     root :to => 'tasks#index', as: :authenticated_root
   end
   unauthenticated :user do #jeśli nie zalogowany
     root :to => 'devise/sessions#new', as: :unauthenticated_root
   end
  end

  # Linki do panelu administracyjnego
  namespace :admin do
    # get "home/index" # Strona główna panelu adminisracyjnego
    get "dashboard" => 'home#index', as: :dashboard # Strona główna panelu adminisracyjnego
    resources :users
    get 'users/:id/gen_password' => 'users#gen_new_pass', as: :new_password_gen
    resources :roles, only: [:index, :edit, :update]
    get "logs" => 'logs#list', as: :logs #Logi
  end

  resources :tasks do
   resources :items

   # Odepnij sprzęt od zlecenia
   get 'items/:id/remove_from_task' => 'items#remove_from_task', as: :remove_item

   # Przypnij sprzęt do zlecenia
   get 'items/:id/add_to_task' => 'items#add_to_task', as: :add_item

   # Lista klientów do możliwych do dodania do zgłoszenia
   get '/:id/clients' => 'users#clients_list_to_task', as: :clients, on: :collection
   get '/:task_id/client/new' => 'users#new_client_to_task', as: :new_client, on: :collection
   get '/:task_id/clients/:id/add_to_task' => 'users#add_to_task', as: :add_client, on: :collection
   get '/:task_id/clients/:id/remove_from_task' => 'users#remove_from_task', as: :remove_client, on: :collection
   post '/clients' => 'users#create_task_client'
  end

  get 'archive' => 'tasks#archive', as: :archive

  resources :users

  # linki do klientów, zwenętrznej
  get 'clients' => 'users#clients', as: :clients_list
  get 'client/new' => 'users#new_client', as: :client_new
  post 'users/create_client'
  get 'client/:id' => 'users#show_client', as: :show_client
  get 'client/:id/edit' => 'users#edit', as: :edit_client
  delete 'client/:id' => 'users#destroy', as: :del_client
  put 'client/:id' => 'users#update'
  patch 'client/:id' => 'users#update' 
  get 'clients/:id/new/password' => 'users#pass_restart', as: :password_gen

  # linki do sprzętów, zwenętrznej
  get 'items' => 'items#items_list', as: :items_list
  get 'item/new' => 'items#item_new', as: :item_new
  post 'items/item_create'
  get 'item/:id' => 'items#item_show', as: :show_item
  get 'item/:id/edit' => 'items#item_edit', as: :edit_item
  delete 'item/delete/:id' => 'items#item_destroy', as: :del_item
  put 'item/:id/update' => 'items#item_update'
  patch 'item/:id/update' => 'items#item_update' 

  # Linki zarządzające profilem użytkownika
  get 'profile/:id' => 'users#profile', as: :profile
  get 'profile/:id/edit' => 'users#edit_profile', as: :profile_edit
  get 'profile/:id/password' => 'users#change_password', as: :profile_password
  put 'profile/:id' => 'users#profile_update'  # update profilu
  patch 'profile/:id' => 'users#profile_update' # update profilu
  put 'profile/:id/password' => 'users#password_update' # zmiana hasła
  patch 'profile/:id/password' => 'users#password_update' # zmiana hasła

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="col-md-12">
				<!-- flash masseges -->
				<div>
				  	<% if value.is_a?(String) %>
				    <div class="<%= flash_class(key) %> fade in alert-dismissable">
				    	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				    	<%= value %>
				    </div>
				    <% end %>
				</div>		
			</div>
		</div>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-md-12">
			<nav class="navbar navbar-default" role="navigation">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<%= link_to ("System <i class=\"fa fa-life-ring\"></i>bsługi Serwisów").html_safe, authenticated_root_path, class: "navbar-brand" %>
					</div>

					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav">
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-tasks"></i> Zlecenia <b class="caret"></b></a>
								<ul class="dropdown-menu">
									<li><%= link_to "Lista zgłoszeń", tasks_path, class: "active" %></li>
									<li><%= link_to "Archiwum zgłoszeń", archive_path %></li>
									<% if can? :create, Task %>
									<li class="divider"></li>
									<li><%= link_to "Utwórz nowe zgłoszenie", new_task_path %></li>
									<% end %>
								</ul>
							</li>
							<% if can? :create, Item %>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-hdd"></span> Sprzęt <b class="caret"></b>
									<ul class="dropdown-menu">
										<li><%= link_to "Lista kart sprzętów", items_list_path %></li>
										<li class="divider"></li>
										<li><%= link_to "Utwórz nową kartę sprzętu", item_new_path %></li>
									</ul>
							<% end %>

							<% if can? :create, User %>
							<li class="dropdown" >
								<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-users"></i> Klienci <b class="caret"></b>
									<ul class="dropdown-menu">
										<li><%= link_to "Lista klientów", clients_list_path %></li>
										<li class="divider"></li>
										<li><%= link_to "Utwórz nowego klienta", client_new_path %></li>
									</ul>
							</li>
							<% end %>
							<% if current_user.role.name == 'menager' %>
							<li><a href="#"><i class="fa fa-bar-chart-o"></i>
 Panel Kierownika</a></li><% end %>
							<li>
								<%if current_user.role.name == 'admin' %>
									<%= link_to admin_dashboard_path, class: "navbar-link" do %>
										<i class="fa fa-laptop"></i> Panel Administracyjny
									<% end %>
								<% end %>
							</li>
						</ul>

						<ul class="nav navbar-nav navbar-right">
							<li>
							<% if user_signed_in? %>
								<%= link_to profile_path(current_user.id), class: "navbar-link" do %>
									<span class="glyphicon glyphicon-user"></span> Twoje konto
								<% end %>
							<% end %>
							</li>
							<li>
								<%= link_to( destroy_user_session_path, :method => :delete, class: "navbar-link") do %>
										<span class="glyphicon glyphicon-off"></span> Wyloguj
								<% end %>
							</li>
								</ul>
							</li>
						</ul>
					</div><!-- /.navbar-collapse -->
				</div><!-- /.container-fluid -->
			</nav> 
		</div>
	</div>
</div>

app/views/layouts/_navigation_admin.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-md-12">
			<nav class="navbar navbar-default" role="navigation">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<%= link_to admin_dashboard_path, class: "navbar-brand" do %>
							<i class="fa fa-rocket fa-fw"></i> Kokpit Administrcyjny

						<% end %>
					</div>

					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav">
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-users fa-fw"></i> Użytkownicy <b class="caret"></b></a>
								<ul class="dropdown-menu">
									<li><%= link_to "Lista użytkowników", admin_users_path, class: "active" %></li>
									<li class="divider"></li>
									<li><%= link_to "Dodaj użytkownika", new_admin_user_path %></li>
								</ul>
							</li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-tag fa-fw"></i> Role <b class="caret"></b></a>
								<ul class="dropdown-menu">
									<li><%= link_to "Lista ról", admin_roles_path, class: "active" %></li>
									<!--<li class="divider"></li>
									<li><%#= link_to "Dodaj nową rolę", new_admin_role_path %></li> -->
								</ul>
							</li>
							
							<li>
								<%= link_to admin_logs_path do %>
									<i class="fa fa-eye fa-fw"></i> Logi Systemowe
								<% end %>
							</li>
						</ul>

						<ul class="nav navbar-nav navbar-right">
							<li>
								<%= link_to authenticated_root_path, class: "navbar-link" do %>
									<span class="glyphicon glyphicon-circle-arrow-left"></span> Wróć do strony
								<% end %>
							</li>
							<li>
								<%= link_to( destroy_user_session_path, :method => :delete, class: "navbar-link") do %>
										<span class="glyphicon glyphicon-off"></span> Wyloguj
								<% end %>
							</li>
								</ul>
							</li>
						</ul>
					</div><!-- /.navbar-collapse -->
				</div><!-- /.container-fluid -->
			</nav> 
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_tiltle(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

   <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
</head>
<body>
	<% if user_signed_in? %><%= render 'layouts/navigation' %><% end %>
	<%= render 'layouts/flash_messages' %>
	<%= yield %>
</body>
</html>